# Generated by Django 4.2.1 on 2023-09-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfurnitures', '0002_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(default='allfurnitures/furnitures/default.jpg', upload_to='allfurnitures/furnitures'),
        ),
    ]
