# Generated by Django 4.2.1 on 2023-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfurnitures', '0007_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='allfurnitures/users/default.jpg', upload_to='allfurnitures/users'),
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='allfurnitures.furniture'),
        ),
    ]
